
// Article
export const ACTION_GET_ARTICLES_STARTED = "GET_ARTICLES_STARTED";
export const ACTION_GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";

export const ACTION_CREATE_ARTICLE_STARTED = "CREATE_ARTICLE_STARTED";
export const ACTION_CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

