// Comment
export const ACTION_GET_COMMENTS_STARTED = "GET_COMMENTS_STARTED";
export const ACTION_GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const ACTION_GET_COMMENTS_FAILED = "GET_COMMENTS_FAILED";

export const ACTION_CREATE_COMMENT_STARTED = "CREATE_COMMENT_STARTED";
export const ACTION_CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const ACTION_CREATE_COMMENTS_FAILED = "CREATE_COMMENTS_FAILED";

// Article
export const ACTION_GET_ARTICLES_STARTED = "GET_ARTICLES_STARTED";
export const ACTION_GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const ACTION_GET_ARTICLES_FAILED = "GET_ARTICLES_FAILED";

export const ACTION_GET_ARTICLES_CAT_STARTED = "GET_ARTICLES_CAT_STARTED";
export const ACTION_GET_ARTICLES_CAT_SUCCESS = "GET_ARTICLES_CAT_SUCCESS";
export const ACTION_GET_ARTICLES_CAT_FAILED = "GET_ARTICLES_CAT_FAILED";

export const ACTION_GET_ARTICLE_STARTED = "GET_ARTICLE_STARTED";
export const ACTION_GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";

export const ACTION_GET_FIRST_ARTICLE_STARTED = "GET_FIRST_ARTICLE_STARTED";
export const ACTION_GET_FIRST_ARTICLE_SUCCESS = "GET_FIRST_ARTICLE_SUCCESS";

export const ACTION_GET_SOME_ARTICLE_STARTED = "GET_SOME_ARTICLES_STARTED";
export const ACTION_GET_SOME_ARTICLE_SUCCESS = "GET_SOME_ARTICLES_SUCCESS";

export const ACTION_CREATE_ARTICLE_STARTED = "CREATE_ARTICLE_STARTED";
export const ACTION_CREATE_ARTICLE_SUCCESS = "CREATE_POST_SUCCESS";

// User
export const ACTION_GET_USER_STARTED = "GET_USER_STARTED";
export const ACTION_GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const ACTION_GET_USER_FAILED = "GET_USER_FAILED";

export const ACTION_CREATE_USER_STARTED = "CREATE_USER_STARTED";
export const ACTION_CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const ACTION_LOGIN_STARTED = "LOGIN_STARTED";
export const ACTION_LOGIN_SUCCESS = "LOGIN_SUCCESS";

//Categories
export const ACTION_GET_CATEGORIES_STARTED = "GET_CATEGORIES_STARTED";
export const ACTION_GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const ACTION_GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";
