<<<<<<< HEAD
export const ACTION_GET_COMMENTS_STARTED = "GET_COMMENTS_STARTED";
export const ACTION_GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const ACTION_GET_COMMENTS_FAILED = "GET_COMMENTS_FAILED";
export const ACTION_CREATE_COMMENT_STARTED = "CREATE_COMMENT_STARTED";
export const ACTION_CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
=======

// Article
export const ACTION_GET_ARTICLES_STARTED = "GET_ARTICLES_STARTED";
export const ACTION_GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";

export const ACTION_CREATE_ARTICLE_STARTED = "CREATE_ARTICLE_STARTED";
export const ACTION_CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

>>>>>>> 270eff1d24ddbb201cb8cf6f1e4d95b31e9117d7
