export const ACTION_GET_ARTICLES_STARTED = "GET_ARTICLES_STARTED";
export const ACTION_GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";

export const ACTION_POST_ARTICLES_SUCCESS = "POST_ARTICLES_SUCCESS";
export const ACTION_POST_ARTICLES_STARTED = "POST_ARTICLES_STARTED";
